<a href="https://colab.research.google.com/github/LakshmiAhala/DataScience/blob/main/DS_Assign7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#@title Importing the .csv using pandas

# Importing pandas
import pandas as pd
import numpy

# Reading the contents of the file
filepath = r"/content/raw_titanic_data.csv";
titanic_data = pd.read_csv(filepath)

# Printing the data
titanic_data.head()

,Id,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

# Analysis on data based on Pclass

In [ ]:
#@title Task 1: Perform GroupBy analysis in Excel

####### Completed in Excel #######

![image.png]()

![image.png]()

In [15]:
#@title Task 2: Perform GroupBy analysis in Pandas

from typing import final

# Group data by 'Pclass'
grouped_data = titanic_data.groupby('Pclass')

# Survivors count per passenger class
surv_count_by_class = grouped_data['Survived'].count()
# print('Count of Survivors per Passenger Class: ')
# print(surv_count_by_class)

# Average fare per passenger class
avg_fare_by_class = grouped_data['Fare'].mean()
avg_fare_by_class = round(avg_fare_by_class, 2)
# print('\nAverage Fare per Passenger Class: ')
# print(avg_fare_by_class)

# Average age per passenger class
avg_age_by_class = grouped_data['Age'].mean()
avg_age_by_class = round(avg_age_by_class, 2)
# print('\nAverage Age per Passenger Class:')
# print(avg_age_by_class)

# Creating a dictionary with the data to form a dataframe
final_data = {
    'Passenger Class': surv_count_by_class.index,
    'Survivors Count': surv_count_by_class.values,
    'Average Fare': avg_fare_by_class.values,
    'Average Age': avg_age_by_class.values
}

# Create the DataFrame
final_df = pd.DataFrame(final_data)

# Display the DataFrame
final_df.head()

   Passenger Class  Survivors Count  Average Fare  Average Age
0                1              323         87.51        39.16
1                2              277         21.18        29.51
2                3              709         13.30        24.82

In [32]:
#@title Task 3: Perform Pivot Table Analysis Using Pandas

import pandas as pd

pivot_table = pd.pivot_table(
                       titanic_data,
                       values=['Survived', 'Fare', 'Age'],
                       index=['Pclass'],
                       aggfunc={'Survived': 'count', 'Fare': 'mean', 'Age': 'mean'}
)

pivot_table = pivot_table.rename(
    columns={
        'Survived': 'Survivors Count',
        'Fare': 'Average Fare',
        'Age': 'Average Age'
    }
)
print(pivot_table)

        Average Age  Average Fare  Survivors Count
Pclass
1         39.159930     87.508992              323
2         29.506705     21.179196              277
3         24.816367     13.302889              709

# Insights - Pclass

1] As per the instructions given in the question pdf, I created a Pivot Table in excel. (screenshots are attached)

2] After grouping the data based upon the Pclass, using Pandas I got the average fare and age, and the count of survivors.
In Pclass 1, 323 people survived, 87.51 is the average fare and 39 yrs is the average age.
In Pclass 2, 277 people survived, 21.18 is the average fare and 29 yrs is the average age.
In Pclass 3, 709 people survived, 13.30 is the average fare, and 24 yrs is the average age.

3] Then, I matched the information I got in Python with what I got in Excel, to ensure that they both were the same

4] I compiled all this information into a Pivot Table, using Pandas. Then, I renamed the headings for better readability.

# BONUS

In [30]:
#@title Task 2: Perform GroupBy analysis in Pandas

from typing import final

# Group data by 'Pclass'
bonus_grouped_data = titanic_data.groupby('Embarked')

# Survivors count per passenger class
bonus_surv_count_by_class = bonus_grouped_data['Survived'].count()
# print('Count of Survivors per Port of Boarding: ')
# print(bonus_surv_count_by_class)

# Average fare per passenger class
bonus_avg_fare_by_class = bonus_grouped_data['Fare'].mean()
bonus_avg_fare_by_class = round(bonus_avg_fare_by_class, 2)
# print('\nAverage Fare per Port of Boarding: ')
# print(avg_fare_by_class)

# Average age per passenger class
bonus_avg_age_by_class = bonus_grouped_data['Age'].mean()
bonus_avg_age_by_class = round(bonus_avg_age_by_class, 2)
# print('\nAverage Age per Port of Boarding:')
# print(avg_age_by_class)

# Creating a dictionary with the data to form a dataframe
bonus_final_data = {
    'Embarkment': bonus_surv_count_by_class.index,
    'Survivors Count': bonus_surv_count_by_class.values,
    'Average Fare': bonus_avg_fare_by_class.values,
    'Average Age': bonus_avg_age_by_class.values
}

# Create the DataFrame
bonus_final_df = pd.DataFrame(bonus_final_data)

bonus_final_df.head()

  Embarkment  Survivors Count  Average Fare  Average Age
0          C              270         62.34        32.33
1          Q              123         12.41        28.63
2          S              914         27.42        29.25

In [33]:
#@title Task 3: Perform Pivot Table Analysis Using Pandas
import pandas as pd

bonus_pivot = pd.pivot_table(
                       titanic_data,
                       values=['Survived', 'Fare', 'Age'],
                       index=['Embarked'],
                       aggfunc={'Survived': 'count', 'Fare': 'mean', 'Age': 'mean'}
)

bonus_pivot = bonus_pivot.rename(
    columns={
        'Survived': 'Survivors Count',
        'Fare': 'Average Fare',
        'Age': 'Average Age'
    }
)
print(bonus_pivot)

          Average Age  Average Fare  Survivors Count
Embarked
C           32.332170     62.336267              270
Q           28.630000     12.409012              123
S           29.245205     27.418824              914

# Insights - Embarked

1] As per the instructions given in the question pdf, I created a Pivot Table in excel. (screenshots are attached)

2] After grouping the data based upon the Port of Embarkment, using Pandas I got the average fare and age, and the count of survivors.
In Port C (Cherbourg), 270 people survived, 62.34 is the average fare and 32 yrs is the average age.
In Pclass Q (Queenston), 123 people survived, 12.41 is the average fare and 28 yrs is the average age.
In Pclass S (Southampton), 914 people survived, 27.42 is the average fare, and 29 yrs is the average age.

3] Then, I matched the information I got in Python with what I got in Excel, to ensure that they both were the same

4] I compiled all this information into a Pivot Table, using Pandas. Then, I renamed the headings for better readability.